@startuml
left to right direction
rectangle "Система замовленнь" {
    (Рупора)
    (Замовлення) as Order
    (Зворотній зв'язок) as Feedback
    (Розклад ефірів)
    (Що грає?)
    (Правила)
}

:Користувач: --> Order : Зробити
Order <-- :Модератор: : Обробити / Заблокувати

:Користувач: --> Feedback : Відправити повідомлення
Feedback <-- :Модератор: : Відповісти / Заблокувати

:Користувач: --> (Розклад ефірів) : Подивитися
:Користувач: --> (Правила) : Подивитися
:Користувач: --> (Що грає?) : Подивитися

(Рупора) <-- :Адміністратор: : Вимкнути / Змінити гучність


':Користувач: -> Order
':Користувач: -> Feedback
':Користувач: -> Rules
':Користувач: -> Timetable

@enduml