@startuml
actor Користувач order 1
actor Модератор order 3
entity "Система замовлень" as Бот order 2

Користувач -> Бот: Назва пісні
note over Бот: Пошук аудіофалу та тексту пісні по назві. \n Опрацювання тексту пісні (цензура).
Користувач <- Бот: Пісня (аудіофайл), \nПопередження (якщо є)

...

Користувач -> Бот : Вибір дня
Користувач <- Бот : Список вільних ефірів

...

Користувач -> Бот : Вибір ефіру
Бот -> Модератор : Пісня, замовник, день+ефір, попередження \n [Прийняти] [Відхилити] [Переглянути текст]
Користувач <- Бот : Пісня відправлена на модерацію

...
... Модератор слухає пісню / дивиться текст ...
...

Модератор -> Бот : Пісня прийнята
note over Бот: Пісня додається до бази данних. \n Обраховується час, коли вона заграє.


Бот -> Користувач : Пісня прийнята, точний час у ефірі

...
... Грають попередні замовлення ...
...


Бот -> Користувач : Повідомлення, що пісня у ефірі

@enduml