@startuml

User -> Bot: Название песни

Bot -> SearchBackend: Поиск песен
Bot <- SearchBackend: Результат

'Bot -> Google: Поиск по названию песни
'Bot <- Google: Результат
'
'Bot -> Genius: Поиск по названию песни
'Bot <- Genius: Результат (текст песни)

User <- Bot: Песня (аудиофайл), \nпредупреждения (если есть)

User -> Bot : Выбор дня
User <- Bot : Список эфиров \n(и ограничений по времени)

User -> Bot : Выбор эфира
Bot -> Moderation : Песня, заказчик, эфир, предупреждения \n [Принять] [Отклонить] [Посмотреть текст]
User <- Bot : Песня отправлена на модерацию


Moderation -> Bot : Песня отмодерирована
Bot -> Player : Скачать песню и добавить в плейлист
Bot -> User : Результат модерации

Player -> Bot : Песня заиграла
Bot -> User : Песня заиграла

@enduml